lang: da
format:
    pdf:
        papersize: "a4"
        geometry:
            - top=2.5cm
            - bottom=2.5cm
            - left=2cm
            - right=2cm
        documentclass: "article"
        include-in-header:
            text: |
                \usepackage{icomma}
                \usepackage{lastpage}
                \usepackage{fancyhdr}
                \pagestyle{fancy}
                \fancyhf{} 
                \renewcommand{\headrulewidth}{0pt}
                \lhead{ Matematik }
                \chead{ 17/01/2024 }
                \rhead{ 1. x }
                \cfoot{Side \thepage\ af \pageref*{LastPage}}
        include-before-body:
            text: |
                \thispagestyle{fancy}